# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
